### ISSUE TITLE
insert/update之后对象变成了加密后对象

### ISSUE THREAD

**Issue by Chameleons18** [baomidou/mybatis-mate-examples#1]
问题：执行完insert/update语句之后，对象中属性被加密，如果后续需要获取对象里面的值，还需要重新查询一遍数据库。
思考：如果加密前将参数对象copy为新对象是否更好一点，还是说这样没有必要？是否因为考虑性能问题没有加拷贝对象的处理？毕竟正常开发过程中很少会在插入数据库之后再去处理原对象。如果想这样，如执行insert/update语句后打印日志，有没有比较好的方式处理。
当前处理方式：Class.newInstance()然后BeanUtils.copyProperties()；JSON.parseObject(JSON.toJsonString(),class)。

**Comment by Chameleons18** [comment]
解决办法二：先不查询，而是构建数据库实体类对象直接进行update，然后根据返回结果判断是否成功，成功后如果需要用到数据则再查询数据库就可以了。但更新后打印日志还是密文，无法从脱敏日志直观看到数据长度，相比较而言解决办法一中在MyBatis拦截器中拷贝新对象来处理更好一点。

**Comment by qmdx** [comment]
实体属性会回写，你可以NEW 新的对象入库
